# Form implementation generated from reading ui file 'app/ui/main/page/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(756, 509)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_preview = QtWidgets.QWidget(parent=Form)
        self.widget_preview.setObjectName("widget_preview")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_preview)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_preview = QtWidgets.QLabel(parent=self.widget_preview)
        self.label_preview.setMinimumSize(QtCore.QSize(0, 0))
        self.label_preview.setObjectName("label_preview")
        self.gridLayout_3.addWidget(self.label_preview, 0, 0, 1, 2)
        self.pushButton_previewOpen = QtWidgets.QPushButton(parent=self.widget_preview)
        self.pushButton_previewOpen.setMinimumSize(QtCore.QSize(160, 0))
        self.pushButton_previewOpen.setObjectName("pushButton_previewOpen")
        self.gridLayout_3.addWidget(self.pushButton_previewOpen, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.widget_preview, 0, 0, 1, 1)
        self.widget_detail = QtWidgets.QWidget(parent=Form)
        self.widget_detail.setObjectName("widget_detail")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_detail)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_details = QtWidgets.QLabel(parent=self.widget_detail)
        self.label_details.setObjectName("label_details")
        self.gridLayout_2.addWidget(self.label_details, 0, 0, 1, 1)
        self.listView_details = QtWidgets.QListView(parent=self.widget_detail)
        self.listView_details.setObjectName("listView_details")
        self.gridLayout_2.addWidget(self.listView_details, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_detail, 0, 1, 1, 1)
        self.widget_task = QtWidgets.QWidget(parent=Form)
        self.widget_task.setObjectName("widget_task")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_task)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView_task = QtWidgets.QTableView(parent=self.widget_task)
        self.tableView_task.setObjectName("tableView_task")
        self.gridLayout.addWidget(self.tableView_task, 1, 0, 1, 1)
        self.label_task = QtWidgets.QLabel(parent=self.widget_task)
        self.label_task.setObjectName("label_task")
        self.gridLayout.addWidget(self.label_task, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_task, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_preview.setText(_translate("Form", "Preview"))
        self.pushButton_previewOpen.setText(_translate("Form", "Open"))
        self.label_details.setText(_translate("Form", "Details"))
        self.label_task.setText(_translate("Form", "Task"))
