# Form implementation generated from reading ui file 'app/ui/main/main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 503)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        self.label_programName = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_programName.setObjectName("label_programName")
        self.horizontalLayout_header.addWidget(self.label_programName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_header.addItem(spacerItem)
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_username.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_username.setObjectName("label_username")
        self.horizontalLayout_header.addWidget(self.label_username)
        self.label_userimage = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_userimage.setObjectName("label_userimage")
        self.horizontalLayout_header.addWidget(self.label_userimage)
        self.gridLayout.addLayout(self.horizontalLayout_header, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.tabWidget.addTab(self.dashboard, "")
        self.launcher = QtWidgets.QWidget()
        self.launcher.setObjectName("launcher")
        self.tabWidget.addTab(self.launcher, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout_footer = QtWidgets.QHBoxLayout()
        self.horizontalLayout_footer.setObjectName("horizontalLayout_footer")
        self.pushButton_logOut = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_logOut.setObjectName("pushButton_logOut")
        self.horizontalLayout_footer.addWidget(self.pushButton_logOut)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_footer.addItem(spacerItem1)
        self.label_credit = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_credit.setObjectName("label_credit")
        self.horizontalLayout_footer.addWidget(self.label_credit)
        self.label_buildVersion = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_buildVersion.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_buildVersion.setObjectName("label_buildVersion")
        self.horizontalLayout_footer.addWidget(self.label_buildVersion)
        self.gridLayout.addLayout(self.horizontalLayout_footer, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_programName.setText(_translate("MainWindow", "kaikitsu"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_userimage.setText(_translate("MainWindow", "UserImg"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dashboard), _translate("MainWindow", "Dashboard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.launcher), _translate("MainWindow", "Launcher"))
        self.pushButton_logOut.setText(_translate("MainWindow", "LogOut"))
        self.label_credit.setText(_translate("MainWindow", "© 2025 Expi Project. All rights reserved."))
        self.label_buildVersion.setText(_translate("MainWindow", "Beta v0.0.1"))
